### ISSUE TITLE
Facilitate clic on link

### ISSUE THREAD

**Issue by philjeudy** [accretio/feedback#1]
When you wanna copy the link to share the event on external websites, propose a copy on the clipboard while highlighting the whole url, to simplify the procedure.

**Comment by williamleferrand** [comment]
That's a good one, thanks!

**Comment by williamleferrand** [comment]
I added a "copy link to clipboard" button that *should* only show up on desktop devices (or android devices that allow copying to the clipboard). It won't appear on Android devices. I still need to tweak the design to make it look good on all platform, but the basic feature is here

**Comment by philjeudy** [comment]
So, closed for good?!

**Comment by williamleferrand** [comment]
try it out!

**Comment by williamleferrand** [comment]
try it out!

On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com> wrote:

> So, closed for good?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accretio/feedback/issues/1#issuecomment-89714839>.
>



-- 
William Le Ferrand

Speed matters : http://www.corefarm.com

Mobile : (+1) (415) 683-1484
Web : http://williamleferrand.github.com/

**Comment by philjeudy** [comment]
T'as pas vu une petite poussée de fievre sur le site ? Encephalograme plat?

On Sat, Apr 4, 2015 at 9:40 PM, William Le Ferrand <notifications@github.com
> wrote:

> try it out!
>
> On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com>
> wrote:
>
> > So, closed for good?!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/accretio/feedback/issues/1#issuecomment-89714839>.
> >
>
>
>
> --
> William Le Ferrand
>
> Speed matters : http://www.corefarm.com
>
> Mobile : (+1) (415) 683-1484
> Web : http://williamleferrand.github.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accretio/feedback/issues/1#issuecomment-89715299>.
>



-- 

[image: --]

Phil Jeudy
[image: http://]about.me/philjeudy
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=a3ba44b7-1933-4eba-edd4-5ab706ba901e>

**Comment by williamleferrand** [comment]
petite poussée (le pic est à 88)



On Sat, Apr 4, 2015 at 9:49 PM, PHIL JEUDY <notifications@github.com> wrote:

> T'as pas vu une petite poussée de fievre sur le site ? Encephalograme plat?
>
> On Sat, Apr 4, 2015 at 9:40 PM, William Le Ferrand <
> notifications@github.com
> > wrote:
>
> > try it out!
> >
> > On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com>
> > wrote:
> >
> > > So, closed for good?!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/accretio/feedback/issues/1#issuecomment-89714839>.
> > >
> >
> >
> >
> > --
> > William Le Ferrand
> >
> > Speed matters : http://www.corefarm.com
> >
> > Mobile : (+1) (415) 683-1484
> > Web : http://williamleferrand.github.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/accretio/feedback/issues/1#issuecomment-89715299>.
> >
>
>
>
> --
>
> [image: --]
>
> Phil Jeudy
> [image: http://]about.me/philjeudy
> <
> http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=a3ba44b7-1933-4eba-edd4-5ab706ba901e
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accretio/feedback/issues/1#issuecomment-89716154>.
>



-- 
William Le Ferrand

Speed matters : http://www.corefarm.com

Mobile : (+1) (415) 683-1484
Web : http://williamleferrand.github.com/

**Comment by philjeudy** [comment]
bon j'ai teste ca marche

On Sat, Apr 4, 2015 at 9:51 PM, William Le Ferrand <notifications@github.com
> wrote:

> petite poussée (le pic est à 88)
>
>
>
> On Sat, Apr 4, 2015 at 9:49 PM, PHIL JEUDY <notifications@github.com>
> wrote:
>
> > T'as pas vu une petite poussée de fievre sur le site ? Encephalograme
> plat?
> >
> > On Sat, Apr 4, 2015 at 9:40 PM, William Le Ferrand <
> > notifications@github.com
> > > wrote:
> >
> > > try it out!
> > >
> > > On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com>
> > > wrote:
> > >
> > > > So, closed for good?!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/accretio/feedback/issues/1#issuecomment-89714839
> >.
> > > >
> > >
> > >
> > >
> > > --
> > > William Le Ferrand
> > >
> > > Speed matters : http://www.corefarm.com
> > >
> > > Mobile : (+1) (415) 683-1484
> > > Web : http://williamleferrand.github.com/
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/accretio/feedback/issues/1#issuecomment-89715299>.
> > >
> >
> >
> >
> > --
> >
> > [image: --]
> >
> > Phil Jeudy
> > [image: http://]about.me/philjeudy
> > <
> >
> http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=a3ba44b7-1933-4eba-edd4-5ab706ba901e
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/accretio/feedback/issues/1#issuecomment-89716154>.
>
> >
>
>
>
> --
> William Le Ferrand
>
> Speed matters : http://www.corefarm.com
>
> Mobile : (+1) (415) 683-1484
> Web : http://williamleferrand.github.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accretio/feedback/issues/1#issuecomment-89716215>.
>



-- 

[image: --]

Phil Jeudy
[image: http://]about.me/philjeudy
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=68d7bd47-69b8-41fc-dd3f-7a55b890c8ba>

**Comment by williamleferrand** [comment]
et là dedans, 7 clics sur le bouton "I'm in" (après les gens bouncent sur
la page de connexion, mais c'est une autre histoire)



On Sat, Apr 4, 2015 at 9:50 PM, William Le Ferrand <william@corefarm.com>
wrote:

> petite poussée (le pic est à 88)
>
>
>
> On Sat, Apr 4, 2015 at 9:49 PM, PHIL JEUDY <notifications@github.com>
> wrote:
>
>> T'as pas vu une petite poussée de fievre sur le site ? Encephalograme
>> plat?
>>
>> On Sat, Apr 4, 2015 at 9:40 PM, William Le Ferrand <
>> notifications@github.com
>> > wrote:
>>
>> > try it out!
>> >
>> > On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com>
>> > wrote:
>> >
>> > > So, closed for good?!
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/accretio/feedback/issues/1#issuecomment-89714839
>> >.
>> > >
>> >
>> >
>> >
>> > --
>> > William Le Ferrand
>> >
>> > Speed matters : http://www.corefarm.com
>> >
>> > Mobile : (+1) (415) 683-1484
>> > Web : http://williamleferrand.github.com/
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/accretio/feedback/issues/1#issuecomment-89715299>.
>> >
>>
>>
>>
>> --
>>
>> [image: --]
>>
>> Phil Jeudy
>> [image: http://]about.me/philjeudy
>> <
>> http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=a3ba44b7-1933-4eba-edd4-5ab706ba901e
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/accretio/feedback/issues/1#issuecomment-89716154>.
>>
>
>
>
> --
> William Le Ferrand
>
> Speed matters : http://www.corefarm.com
>
> Mobile : (+1) (415) 683-1484
> Web : http://williamleferrand.github.com/
>



-- 
William Le Ferrand

Speed matters : http://www.corefarm.com

Mobile : (+1) (415) 683-1484
Web : http://williamleferrand.github.com/

**Comment by williamleferrand** [comment]
youpi

On Sat, Apr 4, 2015 at 9:53 PM, PHIL JEUDY <notifications@github.com> wrote:

> bon j'ai teste ca marche
>
> On Sat, Apr 4, 2015 at 9:51 PM, William Le Ferrand <
> notifications@github.com
>
> > wrote:
>
> > petite poussée (le pic est à 88)
> >
> >
> >
> > On Sat, Apr 4, 2015 at 9:49 PM, PHIL JEUDY <notifications@github.com>
> > wrote:
> >
> > > T'as pas vu une petite poussée de fievre sur le site ? Encephalograme
> > plat?
> > >
> > > On Sat, Apr 4, 2015 at 9:40 PM, William Le Ferrand <
> > > notifications@github.com
> > > > wrote:
> > >
> > > > try it out!
> > > >
> > > > On Sat, Apr 4, 2015 at 9:38 PM, PHIL JEUDY <notifications@github.com
> >
> > > > wrote:
> > > >
> > > > > So, closed for good?!
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/accretio/feedback/issues/1#issuecomment-89714839
> > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > William Le Ferrand
> > > >
> > > > Speed matters : http://www.corefarm.com
> > > >
> > > > Mobile : (+1) (415) 683-1484
> > > > Web : http://williamleferrand.github.com/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/accretio/feedback/issues/1#issuecomment-89715299
> >.
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > [image: --]
> > >
> > > Phil Jeudy
> > > [image: http://]about.me/philjeudy
> > > <
> > >
> >
> http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=a3ba44b7-1933-4eba-edd4-5ab706ba901e
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/accretio/feedback/issues/1#issuecomment-89716154>.
> >
> > >
> >
> >
> >
> > --
> > William Le Ferrand
> >
> > Speed matters : http://www.corefarm.com
> >
> > Mobile : (+1) (415) 683-1484
> > Web : http://williamleferrand.github.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/accretio/feedback/issues/1#issuecomment-89716215>.
> >
>
>
>
> --
>
> [image: --]
>
> Phil Jeudy
> [image: http://]about.me/philjeudy
> <
> http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MPpYqW1p7-_j7d-k6zVdDPP256dQnnf4rdnQg02?t=http%3A%2F%2Fabout.me%2Fphiljeudy&si=4635648473432064&pi=68d7bd47-69b8-41fc-dd3f-7a55b890c8ba
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accretio/feedback/issues/1#issuecomment-89716246>.
>



-- 
William Le Ferrand

Speed matters : http://www.corefarm.com

Mobile : (+1) (415) 683-1484
Web : http://williamleferrand.github.com/
